@startuml
'https://plantuml.com/sequence-diagram

class RECT{
-Px
-Py
-Dx
-Dy
+onClick(x,y)
+onMove(x,y)
+onKeyPress(Key)
+Draw_Border(x,y,dx,dy)
+Draw_pic(x,y,dx,dy,pic)
+Draw_fill(x,y,dy,color)
}

class barraTitulo {
-titulo pestaña
+desplazarPestaña()
}
barraTitulo..>RECT

class botonVerde {
-color
-forma
+maximizarPestaña()
}

class botonAmarillo {
-color
-forma
+minimizarPestaña()
}

class botonRojo {
-color
-forma
+cerrarPestaña()
}

class borde {
-Px
-py
+modificarTamaño()
}

class modificadoresPestaña{
-botonVerde
-botonRojo
-botonAmarillo
-borde
}

modificadoresPestaña *-- borde
modificadoresPestaña *-- botonRojo
modificadoresPestaña *-- botonAmarillo
modificadoresPestaña *-- botonVerde

class cuadroDeTexto {
-limitSD
-limitID
-limitSZ
-limitIZ
-posicion
+Escribir(posicion)
}

class Posicion {
-px
-py
+senalarPosicion(px,py)
}


class menuOpciones {
-op1
-op2
-op3
-op4
+elegirOpcion(px,py)
}
class opciones {
-titulo
-dibujo
+buscar()
+verDocumentos()
+compartir()
+reproducir()
}
menuOpciones o-- opciones
RECT <... menuOpciones

RECT <. modificadoresPestaña
RECT <.. cuadroDeTexto

cuadroDeTexto ..>Posicion

class documentos{
-titulo
-imagen
+editarTitulo()
+seleccionarDocumento()
+arrastrarDocumento()
+enviarDocumento()
}
RECT <-.. documentos

class barraInformativa {
-Información Elemento Seleccionado
}





@enduml