@startuml
'https://plantuml.com/sequence-diagram

class pestaña {
-Barra Titulo
-Barra Informativa
-Cuerpo

}

class RECT{
Px
Py
Dx
Dy
onClick(x,y)
onMove(x,y)
onKeyPress(Key)
Draw_Border(x,y,dx,dy)
Draw_pic(x,y,dx,dy,pic)
Draw_fill(x,y,dy,color)
}


class barraTitulo {
-titulo pestaña
-lupa
- ">"
-"<"
-modificadoresPestaña
+desplazarPestaña()
+seleccionarOpcion()
}
barraTitulo..>RECT
barraTitulo--* pestaña

class botonVerde {
-color
-forma
+maximizarPestaña()
}

class botonAmarillo {
-color
-forma
+minimizarPestaña()
}

class botonRojo {
-color
-forma
+cerrarPestaña()
}



class modificadoresPestaña{
-botonVerde
-botonRojo
-botonAmarillo
}


modificadoresPestaña *-- botonRojo
modificadoresPestaña *-- botonAmarillo
modificadoresPestaña *-- botonVerde
modificadoresPestaña --o barraTitulo

class cuadroDeTexto {
-Lim UR
-Lim Ul
-Lim DR
-Lim DL
-posicion
+Escribir(posicion)
}
cuadroDeTexto --* cuerpo

class Posicion {
-px
-py
+señalarPosicion(px,py)
}


class menuOpciones {
-op1
-op2
-op3
-op4
+elegirOpcion(px,py)
}
menuOpciones --* cuerpo

class opciones {
-titulo
-dibujo
+buscar()
+verDocumentos()
+compartir()
+reproducir()
}
menuOpciones *-- opciones



cuadroDeTexto ..>Posicion

class documentos{
-titulo
-imagen
+editarTitulo()
+seleccionarDocumento()
+arrastrarDocumento()
+enviarDocumento()
}

class barraInformativa {
-Información Elemento Seleccionado
-Hora y fecha
}
 barraInformativa -* pestaña


class busqueda {
-icono Lupa
+busquedaEnPestaña(texto)
}
busqueda --o barraTitulo
cuadroDeTexto <.busqueda

class cambioPagina {
-iconoAtras "<"
-iconoAdelante ">"
+irPaginaPrevia()
+irPaginaPost()
}

cambioPagina --o barraTitulo

class cuerpo {
-Cuadro de texto
-Cuadro de dibujo
-Documentos
-Menu opciones
}
documentos --* cuerpo
cuerpo --* pestaña
cuerpo ..> RECT

class cuadroDeDibujo {
-Lim UR
-Lim Ul
-Lim DR
-Lim DL
-posicion
+Dibujar(posicion)
}
cuadroDeDibujo ..> RECT
cuadroDeDibujo --* cuerpo
cuadroDeDibujo ..> Posicion
@enduml